---

syllables:
- position: 1
  segments:
  - probability: 0.1
    phonemes:
    - ["J", 1]
    - ["H", 1]
    - ["C", 1]
    
  - probability: 0.9
    phonemes:         # t d k g f v p b c h s T D l n m j r
    - ["t", 5]
    - ["tc", 1]
    - ["th", 1]
    - ["tj", 1]
    
    - ["d", 4]
    - ["dz", 1]
    - ["dj", 1]
    
    - ["k", 4]
    - ["kc", 1]
    - ["kh", 1]
    - ["kj", 1]
    - ["kT", 1]
    
    - ["g", 4]
    - ["gc", 1]
    - ["gD", 1]
    - ["gj", 1]
    
    - ["f", 3]
    - ["fc", 1]
    - ["fh", 1]
    - ["fj", 1]
    
    - ["v", 1]
    - ["vj", 1]
    
    - ["p", 1]
    - ["pc", 1]
    - ["ph", 1]
    - ["pj", 1]
    - ["pf", 1]
    
    - ["b", 1]
    - ["bj", 1]
    
    - ["h", 1]
    
    - ["s", 1]
    - ["sh", 1]
    - ["sj", 1]
    - ["st", 1]
    - ["sk", 1]
    - ["sf", 1]
    - ["sp", 1]
    - ["sn", 1]
    - ["sm", 1]
    
    - ["T", 1]
    - ["Tj", 1]
    
    - ["D", 1]
    - ["Dj", 1]
    
    - ["l", 1]
    - ["lc", 1]
    - ["lh", 1]
    - ["lj", 1]
    
    - ["n", 1]
    - ["nh", 1]
    - ["nj", 1]
    
    - ["m", 1]
    - ["my", 1]
    
    - ["j", 1]
    
    - ["r", 1]
    - ["rh", 1]
    - ["rj", 1]

  - phonemes:
    - ["a", 5]
    - ["i", 4]
    - ["u", 4]
    - ["e", 3]
    - ["o", 3]

  - probability: 0.1
    phonemes:
    - ["n", 8]
    - ["l", 4]
    - ["x", 1] # repeater
    - ["c", 1]
    - ["h", 1]
    - ["r", 1]

- position: 2
  segments:
  - probability: 0.9
    phonemes:
    - ["t", 5]
    - ["tj", 1]
    
    - ["d", 4]
    - ["dj", 1]
    
    - ["k", 4]
    - ["kj", 1]
    
    - ["g", 4]
    - ["gj", 1]
    
    - ["f", 3]
    - ["fj", 1]
    
    - ["p", 1]
    - ["pj", 1]
    
    - ["b", 1]
    - ["bj", 1]
    
    - ["s", 1]
    - ["sj", 1]
    
    - ["T", 1]
    - ["Tj", 1]
    
    - ["D", 1]
    - ["Dj", 1]
    
    - ["l", 1]
    - ["lc", 1]
    - ["lj", 1]
    
    - ["n", 1]
    - ["ny", 1]
    
    - ["m", 1]
    - ["my", 1]
    
    - ["j", 1]
    
    - ["r", 1]
    - ["rj", 1]

  - phonemes:
    - ["a", 5]
    - ["i", 4]
    - ["u", 4]
    - ["e", 3]
    - ["o", 3]

syllable-balance: [3, 1]

writing-systems:
- transliterations:
  - ["si", "shi"]
  - ["sY", "sh"]
  - ["ti", "chi"]
  - ["hu", "fu"]
  - ["tY", "ch"]
  - ["zi", "ji"]
  - ["zY", "j"]
  - ["d([iu])", "j\\1"]
  - ["N><([aiueo])", "n'><\\1"]
  - ["x><ch", "t><ch"]
  - ["x><(.)(.?)", "\\1><\\1\\2"]
  - ["Y", "y"]
  - ["N", "n"]

  - ["a><a", "ā"]
  - ["u><u", "ū"]
  - ["e><e", "ē"]
  - ["o><[ou]", "ō"]

  - ["[<>]", ""]
